// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOt-wcJCA0KE754nPQoM9JFs55UlKYmSo',
    appId: '1:604946397765:web:f22bb8726bb7e7cd4e412c',
    messagingSenderId: '604946397765',
    projectId: 'note-awe',
    authDomain: 'note-awe.firebaseapp.com',
    storageBucket: 'note-awe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA81ZF9xG9R0Q4Uul8rh0bi3NRkW4HRih4',
    appId: '1:604946397765:android:f81a21c08599f21e4e412c',
    messagingSenderId: '604946397765',
    projectId: 'note-awe',
    storageBucket: 'note-awe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu6zyuQXUyAMEDv8gyObXgNb3m3P7JWIc',
    appId: '1:604946397765:ios:035dde3f6e3e35f84e412c',
    messagingSenderId: '604946397765',
    projectId: 'note-awe',
    storageBucket: 'note-awe.firebasestorage.app',
    androidClientId: '604946397765-u0pbjcrjb4j5f6jvlrf0ebqvk55p7et6.apps.googleusercontent.com',
    iosClientId: '604946397765-5tihvks48unnppj39skje2h6m65fond1.apps.googleusercontent.com',
    iosBundleId: 'com.example.awesomeNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu6zyuQXUyAMEDv8gyObXgNb3m3P7JWIc',
    appId: '1:604946397765:ios:035dde3f6e3e35f84e412c',
    messagingSenderId: '604946397765',
    projectId: 'note-awe',
    storageBucket: 'note-awe.firebasestorage.app',
    androidClientId: '604946397765-u0pbjcrjb4j5f6jvlrf0ebqvk55p7et6.apps.googleusercontent.com',
    iosClientId: '604946397765-5tihvks48unnppj39skje2h6m65fond1.apps.googleusercontent.com',
    iosBundleId: 'com.example.awesomeNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBW6LOBuL28PTO4x5lU7-SMdaTPXmfzV0',
    appId: '1:604946397765:web:0f17308954ed50c94e412c',
    messagingSenderId: '604946397765',
    projectId: 'note-awe',
    authDomain: 'note-awe.firebaseapp.com',
    storageBucket: 'note-awe.firebasestorage.app',
  );

}